---
# Files end up in...
#  [bucket][path]/[object-key]/[object-key]-latest.7z
#  [bucket][path]/[object-key]/[object-key]-[YYYYMMDD]-[HHmm].7z


# System paths
7zip-execPath:      /usr/bin/7z
log-dir:            /home/ubuntu/backups
mysql-backup-dir:   /home/ubuntu/backups


# Configure email notifications
email:
    server:     smtp.mandrillapp.com
    port:       587
    user:       production@example.com
    password:   *******************
    from_email: server-name@example.com
    to_email:   production@example.com
    subject:    Error encounted on SERVERNAME during automated backups


# Defaults
# These will be used for all resources unless otherwise specified
defaults:
    
    # Used to encrypt the archives
    password:   *************
    
    # Default schedule
    schedule:   { "hourly": 0, "daily": 7, "weekly": 4, "monthly": 6 }
    
    # The location backups are saved to
    # Note: you can define other stores elsewhere in the config and reference them from 
    # resource definitions using YAML relational anchors ie. "&" and "*"
    store: 
        type:       s3
        path:       /backups/servername
        bucket:     bigcorp-backups
        accessId:   AKXXXXXXXXXXXXXXXXXX
        secretKey:  **********************************


# Resources
# Various things to be backed up
resources:
    
    # Databases
    wordpress-blah-db:
        schedule:   { "hourly": 48, "daily": 21, "weekly": 8, "monthly": 12 }
        mysql:      { database: "my-wp-site", server: "localhost", user: "root", password: "************"}
    someother-db:
        mysql:      { database: "someother", server: "localhost", user: "root", password: "**********"}
    phpmyadmin-db:
        mysql:      { database: "phpmyadmin", server: "localhost", user: "root", password: "**********"}
    
    # Backup the site files once a day
    hairfree-wwwroot:
        path:       /srv/hairfree/wwwroot

